- .github/workflows/dispatch_workflow.yml
> Manual Workflow

- .github/workflows/ci.yml
- .nvmrc
- package.json
> ci(node): add version

- README.md
> fix(rules): add rules and modify others

- .github/workflows/ci.yml
> fix(gha): add sub develop branches to workflow

- yarn.lock
> fix(npm): vulnerabilities

- .github/workflows/ci.yml
> fix(checks): add name to verify it on each commit

- src/02/index.html
> Style inline

- src/02/index.html
Agregando un estilo de fuente con una modificación de tamaño en el index
> Estilos de Fuente

- src/03/index.html
> Estilo de cabecera

- src/03/index.html
> Lista de hobbies

- README.md
- src/14/media-queries.md
> fix(readme): root links

- .vscode/settings.json
- src/04/index.html
se agregaron algunos colores en lo estilos en  linea en la tabla de horarios
> Css external Style

- src/04/index.html
Se modifico la fuente y se agregaron colores a la fuente
>  Ejercicios de estilos externos 

- src/04/index.css
- src/04/index.html
Agregando una carta con modificaciones de color y fuente con estilos externos
> Estilos externos 

- .vscode/settings.json
- src/07/index.html
- src/08/Style/index.css
- src/08/index.html
"Agregando ejercicios de bordes con diferentes ejemplos"
> border exercises

- src/08/Style/index.css
- src/08/index.html
Agregando segunda parte de del ejercicio de css y se añadieron algunos estilos
> Text exercises 

- package.json
- yarn.lock
> feat(dependencies): upgrade

- .github/workflows/ci.yml
> fix(ci): upgrade node version on ci

- .github/workflows/pr-preview.yml
- build-preview.mjs
- package.json
> feat(deploy): create deploy preview for PRs

- src/10/index.css
- src/10/index.html
Agregando ejercicio de texto con la propiedad transformar
> Transforms

- src/11/index.css
- src/11/index.html
> Animations

- src/pair-programming/index.html
> Conection 

- src/pair-programming/index.html
- src/pair-programming/styles/index.css
Exercise Button 02
Add Button 02
> feat(button): add button 02

- src/pair-programming/index.html
- src/pair-programming/styles/index.css
> feat(button): adding button 4

- src/pair-programming/index.html
- src/pair-programming/styles/index.css
Divider
Adding divider with horizontal rule tag
> feat(divider): add first divider

- src/pair-programming/index.html
- src/pair-programming/styles/index.css
> Add divider
